### PR TITLE
Redirect fix

### PR DESCRIPTION
**Pull request by benbalter**
This PR moves the redirects from `_posts/redirects` to `redirects` and uses a permalink key in the front matter, rather than the file name to set its permalink URL. Since they're pages, not posts, we don't need the date in the front matter, and can exclude them from the sitemap, all of which, should speed things up slightly. To do this, I `git mv _posts/redirects redirects` and then used the following quick script:

```ruby
Dir["./redirects/*"].each do |path|
  data = YAML.load_file(path)
  matches = path.match %r{./redirects/(\d{4})-(\d{2})-(\d{2})-(.*)\.markdown}
  data["permalink"] = "/#{matches[1]}/#{matches[2]}/#{matches[3]}/#{matches[4]}/"
  data["sitemap"]   = false
  data.delete("date")
  File.write path, YAML.dump(data) + "---\n"
end
```

The PR diff is a bit funky, but https://github.com/Haacked/haacked.com/commit/8f2bbe14424c27c3bdb7bece565f7c16f688ae81 should give you a good sample of what's really going on here.

If I understand how redirects are used, the end result should be the same, but they are now pages, not posts, and thus will not appear in the index list, feed, sitemap, etc.

### CODE REVIEW

**Comment by Haacked** [comment]
All the permalinks are missing the original `/archive` portion of the URL. Is that intended? That seems like it would break all my redirects. In your script, the first match is `/#{matches[1]}`. Shouldn't that start at `0`?

**Comment by benbalter** [comment]
@Haacked can you give me an example of where you'd like to redirect from/to?

**Comment by Haacked** [comment]
@benbalter sure! Here's one example:

From: `/archive/0001/01/01/json-hijacking.aspx/`
To: `/archive/2009/06/25/json-hijacking.aspx/`

Ideally, I'd delete everything in `_posts/redirects` and add all of them as `redirect_from` in the front-matter of the target post. But I just haven't had the time to do that. :smile:

**Comment by benbalter** [comment]
It's not particularly pretty, but believe this code should do it then. This PR should now move all the redirects from files in the `_posts/redirects` folder to storing the alias URL as a `redirect_from`

```ruby
require 'yaml'
require 'jekyll'
redirects = Dir["./_posts/redirects/*"]

def path_to_url(path)
  matches = path.match %r{./redirects/(\d{4})-(\d{2})-(\d{2})-(.*)\.markdown}
  "/archive/#{matches[1]}/#{matches[2]}/#{matches[3]}/#{matches[4]}/"
end

def url_to_path(url)
  matches = url.match %r{/archive/(\d{4})/(\d{2})/(\d{2})/(.*)/}
  path = "./_posts/archived/#{matches[1]}-#{matches[2]}-#{matches[3]}-#{matches[4]}.markdown"
  return path if File.exists?(path)

  path = "./_posts/#{matches[1]}/#{matches[1]}-#{matches[2]}-#{matches[3]}-#{matches[4]}.markdown"
  return path if File.exists?(path)
end

redirect_map = {}
redirects.each do |path|
  data = YAML.load_file(path)
  url = path_to_url(path)
  redirect_map[url] = url_to_path(data["redirect_to"])
end

redirects.each do |path|
  data = YAML.load_file(path)
  redirect_path = url_to_path(data["redirect_to"])
  redirect_path = redirect_map[data["redirect_to"]] if redirect_path.nil?
  redirect_from_url = path_to_url(path)

  content = File.read(redirect_path)
  parts = content.split Jekyll::Document::YAML_FRONT_MATTER_REGEXP
  yaml = YAML.load(parts[1])
  yaml["redirect_from"] = [yaml["redirect_from"]] if yaml["redirect_from"].is_a?(String)
  yaml["redirect_from"] ||= []
  yaml["redirect_from"].push(redirect_from_url) unless yaml["redirect_from"].include?(redirect_from_url)
  yaml["redirect_from"] = yaml["redirect_from"].first if yaml["redirect_from"].size == 1

  File.write(redirect_path, YAML.dump(yaml) + "---\n\n" + parts[4])
end
```

**Comment by Haacked** [comment]
I really need to up my Ruby game. Nice!

**Comment by benbalter** [comment]
Just confirmed `haacked.com` no longer redirects, and that `/archive/0001/01/01/json-hijacking.aspx/` redirects to `/archive/2009/06/25/json-hijacking.aspx/`

**Comment by Haacked** [comment]
Thanks a lot @benbalter!

**Pull request merged**
