### PR TITLE
Fix line breaks in code output

### PR DESCRIPTION
**Pull request by grhm**
Your code output isn't displaying on multiple lines as was probably intended.
Makes spotting the change in the hex from line 1 to line 2 hard (as its all one line).

### CODE REVIEW

**Comment by haacked** [comment]
Which browser? Seems fine to me in Chrome and Safari on iOS and Mac.

**Comment by grhm** [comment]
This was on Chrome on Windows, but checking now in Chrome on Android it
appears fine... Hmmmm.

**Comment by grhm** [comment]
Definitely not working on Windows here, in Chrome or Firefox.

Screenshot

**Comment by haacked** [comment]
So weird! Ok, I'll merge this. It'll take a few minutes to build and deploy. Let me know if it looks good in about 15 minutes.

**Comment by grhm** [comment]
Looks good here, both firefox and Chrome on Windows. Cheers.

**Pull request merged**
