### PR TITLE
Update 2015-06-15-the-getting-better-moment.markdown

### PR DESCRIPTION
**Pull request by Mykezero**
Change spelling of 'returend' to 'returned'

### CODE REVIEW

**Comment by Mykezero** [comment]
Also, is the front page suppose to redirect to this blog post and not the one about 'Building an Atom package in ES6'?

**Comment by Haacked** [comment]
> Also, is the front page suppose to redirect to this blog post and not the one about 'Building an Atom package in ES6'? Either way a very interesting read!

Ayiyi. No, it's not supposed to do that. Hey @benbalter, any ideas why that's happening after I merged your PR?

@Mykezero thanks for the typo fix!

**Comment by benbalter** [comment]
Because you're paginating 20 posts per page, with the content, this post (and its associated redirect) are visible on the front page. The quick fix would be to change `redirect` to `redirect_to` on https://github.com/Haacked/haacked.com/blob/gh-pages/index.html#L8, but that's not a great solution, as a page could have 0-20 posts on it, depending on the number of redirects. The smarter option would be to make the redirects not posts... which I can submit a PR to do momentarily.

**Comment by Haacked** [comment]
@benbalter Would love to do whatever you think is the best solution. I have to admit, I'm not sure I fully understand the issue right now.

**Pull request merged**
